# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'InClass07' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for InClass07
  pod 'Alamofire', '~> 4.4'

end
