//
//  DataInfo.swift
//
//  Created by Shehab, Mohamed on 2/20/19.
//  Copyright © 2019 UNCC. All rights reserved.
//

import Foundation

class User {
    var name:String?
    var age:Double?
    var gender:String?
    var group:String?
    var state:String?
    
    init(name: String, age: Double, gender:String, group:String, state:String) {
        self.name = name
        self.age = age
        self.gender = gender
        self.group = group
        self.state = state
    }
}

class DataInfo{
    static public let users:[User] = [
        User(name: "Nevin Hobden", age: 36, gender: "Male", group: "Family", state: "New Mexico"),
        User(name: "Stillman Macken", age: 32, gender: "Male", group: "Family", state: "Arizona"),
        User(name: "Stevy Ranscomb", age: 34, gender: "Male", group: "Work", state: "Arizona"),
        User(name: "Lynelle Garstang", age: 20, gender: "Female", group: "Family", state: "Nebraska"),
        User(name: "Worth Tomek", age: 42, gender: "Male", group: "Friend", state: "Missouri"),
        User(name: "Bob Mendonca", age: 30, gender: "Male", group: "Friend", state: "New York"),
        User(name: "Serene Leeds", age: 40, gender: "Female", group: "Work", state: "California"),
        User(name: "Carin Everley", age: 50, gender: "Female", group: "Friend", state: "Wisconsin"),
        User(name: "Beau Mangham", age: 26, gender: "Male", group: "Family", state: "Louisiana"),
        User(name: "Blithe Sizey", age: 34, gender: "Female", group: "Family", state: "Pennsylvania"),
        User(name: "Rhett Bootland", age: 42, gender: "Male", group: "Friend", state: "Florida"),
        User(name: "Titos Ashwood", age: 28, gender: "Male", group: "Friend", state: "Minnesota"),
        User(name: "Caty Chatteris", age: 22, gender: "Female", group: "Friend", state: "California"),
        User(name: "Taber Gavaghan", age: 42, gender: "Male", group: "Family", state: "Iowa"),
        User(name: "Sadella Meth", age: 44, gender: "Female", group: "Work", state: "Tennessee"),
        User(name: "Patin Asch", age: 36, gender: "Male", group: "Family", state: "Texas"),
        User(name: "Eilis Ratchford", age: 44, gender: "Female", group: "Family", state: "Florida"),
        User(name: "Sammy Scorton", age: 50, gender: "Female", group: "Friend", state: "Nevada"),
        User(name: "Mylo Cropp", age: 34, gender: "Male", group: "Family", state: "Michigan"),
        User(name: "Jessie Brabham", age: 30, gender: "Male", group: "Family", state: "New York"),
        User(name: "Ransom Van Hesteren", age: 50, gender: "Male", group: "Work", state: "Georgia"),
        User(name: "Lonnie Lefeuvre", age: 44, gender: "Male", group: "Family", state: "Florida"),
        User(name: "Eddi Labbett", age: 48, gender: "Female", group: "Friend", state: "Washington"),
        User(name: "Muffin Burdoun", age: 38, gender: "Male", group: "Friend", state: "Florida"),
        User(name: "Richy Siverns", age: 44, gender: "Male", group: "Family", state: "Illinois"),
        User(name: "Benjie O'Henery", age: 38, gender: "Male", group: "Friend", state: "Indiana"),
        User(name: "Loni Snowden", age: 46, gender: "Female", group: "Work", state: "California"),
        User(name: "Thorn Duffet", age: 36, gender: "Male", group: "Friend", state: "Texas"),
        User(name: "Madelyn Ornells", age: 36, gender: "Female", group: "Work", state: "Ohio"),
        User(name: "Lulu Oppie", age: 38, gender: "Female", group: "Family", state: "Maryland"),
        User(name: "Heath Hadkins", age: 30, gender: "Male", group: "Family", state: "Florida"),
        User(name: "Lukas Frensch", age: 50, gender: "Male", group: "Friend", state: "Texas"),
        User(name: "Julieta Kear", age: 46, gender: "Female", group: "Friend", state: "Florida"),
        User(name: "Mahalia Margaritelli", age: 22, gender: "Female", group: "Work", state: "Oklahoma"),
        User(name: "Blair Hansberry", age: 38, gender: "Female", group: "Work", state: "Virginia"),
        User(name: "Guthrey Thomkins", age: 28, gender: "Male", group: "Friend", state: "Massachusetts"),
        User(name: "Erny Dayment", age: 34, gender: "Male", group: "Work", state: "Florida"),
        User(name: "Krystal Bullcock", age: 36, gender: "Female", group: "Work", state: "Kansas"),
        User(name: "Min Perroni", age: 46, gender: "Female", group: "Work", state: "Connecticut"),
        User(name: "Jessica Spurrier", age: 50, gender: "Female", group: "Friend", state: "Arkansas"),
        User(name: "Cathie Kornacki", age: 40, gender: "Female", group: "Work", state: "New Jersey"),
        User(name: "Gerik Eard", age: 48, gender: "Male", group: "Family", state: "Virginia"),
        User(name: "Raff Symmons", age: 48, gender: "Male", group: "Friend", state: "Florida"),
        User(name: "Sashenka Chase", age: 32, gender: "Female", group: "Work", state: "Texas"),
        User(name: "Prue Strute", age: 50, gender: "Female", group: "Family", state: "Virginia"),
        User(name: "Kym Tapner", age: 40, gender: "Female", group: "Work", state: "New York"),
        User(name: "Jaymie Klosges", age: 24, gender: "Male", group: "Friend", state: "Massachusetts"),
        User(name: "Tally Pickover", age: 22, gender: "Male", group: "Work", state: "Tennessee"),
        User(name: "Creight Sacher", age: 30, gender: "Male", group: "Work", state: "Arizona"),
        User(name: "Justis Shortell", age: 34, gender: "Male", group: "Friend", state: "Colorado"),
        User(name: "Neill Allam", age: 36, gender: "Male", group: "Work", state: "California"),
        User(name: "Sunshine Ellery", age: 32, gender: "Female", group: "Family", state: "New Jersey"),
        User(name: "Mirella Kennedy", age: 40, gender: "Female", group: "Family", state: "Tennessee"),
        User(name: "Berkley Seak", age: 42, gender: "Male", group: "Friend", state: "Indiana"),
        User(name: "Bradley Swett", age: 38, gender: "Male", group: "Family", state: "Missouri"),
        User(name: "Ottilie Haggerty", age: 38, gender: "Female", group: "Friend", state: "California"),
        User(name: "Dixie Chestnutt", age: 50, gender: "Female", group: "Work", state: "Mississippi"),
        User(name: "Caterina O'Cooney", age: 42, gender: "Female", group: "Family", state: "Texas"),
        User(name: "Georgine Zarfat", age: 20, gender: "Female", group: "Friend", state: "Illinois"),
        User(name: "Isaac McKinlay", age: 36, gender: "Male", group: "Work", state: "Louisiana"),
        User(name: "Walt Eberst", age: 34, gender: "Male", group: "Friend", state: "Georgia"),
        User(name: "Vernor Allport", age: 22, gender: "Male", group: "Friend", state: "Texas"),
        User(name: "Barby Thomann", age: 22, gender: "Female", group: "Work", state: "Wisconsin"),
        User(name: "Darrin Minithorpe", age: 42, gender: "Male", group: "Work", state: "Minnesota"),
        User(name: "Hatti Stather", age: 38, gender: "Female", group: "Work", state: "South Carolina"),
        User(name: "Sascha Umfrey", age: 24, gender: "Male", group: "Family", state: "California"),
        User(name: "Valdemar Garrie", age: 44, gender: "Male", group: "Work", state: "Minnesota"),
        User(name: "Hashim Ebbage", age: 42, gender: "Male", group: "Family", state: "Alabama"),
        User(name: "Parke Gladyer", age: 28, gender: "Male", group: "Friend", state: "Virginia"),
        User(name: "Karlene Franschini", age: 42, gender: "Female", group: "Work", state: "Alabama"),
        User(name: "Alair Calabry", age: 32, gender: "Male", group: "Family", state: "Oklahoma"),
        User(name: "Lionello Apfel", age: 22, gender: "Male", group: "Work", state: "Texas"),
        User(name: "Elva Gregorio", age: 50, gender: "Female", group: "Work", state: "Iowa"),
        User(name: "Rawley Vispo", age: 30, gender: "Male", group: "Friend", state: "Texas"),
        User(name: "Merissa Hampstead", age: 42, gender: "Female", group: "Friend", state: "New York"),
        User(name: "Saudra Blasetti", age: 34, gender: "Female", group: "Friend", state: "Minnesota"),
        User(name: "Casey How", age: 22, gender: "Male", group: "Friend", state: "Texas"),
        User(name: "Ed Zoephel", age: 22, gender: "Male", group: "Friend", state: "Georgia"),
        User(name: "Maximo Wallen", age: 50, gender: "Male", group: "Family", state: "Florida"),
        User(name: "Bobine O'Doherty", age: 26, gender: "Female", group: "Family", state: "California"),
        User(name: "Shirline Deem", age: 36, gender: "Female", group: "Family", state: "Colorado"),
        User(name: "Brandyn Pisculli", age: 30, gender: "Male", group: "Work", state: "Maryland"),
        User(name: "Natty Patty", age: 28, gender: "Male", group: "Friend", state: "California"),
        User(name: "Foster McShirie", age: 42, gender: "Male", group: "Family", state: "North Carolina"),
        User(name: "Jarrid Crighton", age: 28, gender: "Male", group: "Work", state: "Texas"),
        User(name: "Suki Easthope", age: 36, gender: "Female", group: "Family", state: "Florida"),
        User(name: "El Furlow", age: 48, gender: "Male", group: "Friend", state: "Texas"),
        User(name: "Kahaleel Fidele", age: 24, gender: "Male", group: "Friend", state: "Indiana"),
        User(name: "Amandy Shattock", age: 26, gender: "Female", group: "Friend", state: "Florida"),
        User(name: "Kerk Kull", age: 22, gender: "Male", group: "Family", state: "California"),
        User(name: "Phyllis Slograve", age: 48, gender: "Female", group: "Family", state: "Massachusetts"),
        User(name: "Fairfax Lovejoy", age: 20, gender: "Male", group: "Family", state: "Arizona"),
        User(name: "Steven Patrickson", age: 24, gender: "Male", group: "Friend", state: "Colorado"),
        User(name: "Goldy Christie", age: 42, gender: "Female", group: "Family", state: "Kansas"),
        User(name: "Basilius Leschelle", age: 42, gender: "Male", group: "Work", state: "Washington"),
        User(name: "Dee Grass", age: 20, gender: "Female", group: "Friend", state: "Maryland"),
        User(name: "Rosalinde Punyer", age: 30, gender: "Female", group: "Work", state: "Oklahoma"),
        User(name: "Naomi Leiden", age: 46, gender: "Female", group: "Work", state: "Texas"),
        User(name: "Wylma Tuffs", age: 32, gender: "Female", group: "Friend", state: "New York"),
        User(name: "Vere McGannon", age: 28, gender: "Female", group: "Work", state: "Delaware"),
        User(name: "Yasmin Antos", age: 40, gender: "Female", group: "Friend", state: "Florida"),
        User(name: "Lovell Aleshintsev", age: 44, gender: "Male", group: "Friend", state: "Texas"),
        User(name: "Ree Outhwaite", age: 50, gender: "Female", group: "Family", state: "District of Columbia"),
        User(name: "Norman Maddick", age: 30, gender: "Male", group: "Friend", state: "California"),
        User(name: "Nobe Wedlock", age: 40, gender: "Male", group: "Family", state: "Wisconsin"),
        User(name: "Raychel Compson", age: 32, gender: "Female", group: "Friend", state: "California"),
        User(name: "Vassily Campos", age: 42, gender: "Male", group: "Family", state: "Ohio"),
        User(name: "Adelaide Tolle", age: 40, gender: "Female", group: "Family", state: "District of Columbia"),
        User(name: "Giuseppe Greystoke", age: 48, gender: "Male", group: "Friend", state: "Texas"),
        User(name: "Riobard Bradfield", age: 38, gender: "Male", group: "Work", state: "Tennessee"),
        User(name: "Gilli Jerman", age: 42, gender: "Female", group: "Friend", state: "New Mexico"),
        User(name: "Brod Thams", age: 28, gender: "Male", group: "Family", state: "Virginia"),
        User(name: "Nappy Shotbolt", age: 38, gender: "Male", group: "Family", state: "Missouri"),
        User(name: "Sigismond Stebbings", age: 46, gender: "Male", group: "Friend", state: "Tennessee"),
        User(name: "Candie Blaszkiewicz", age: 44, gender: "Female", group: "Friend", state: "Colorado"),
        User(name: "Ramona Baum", age: 20, gender: "Female", group: "Friend", state: "Louisiana"),
        User(name: "Kiah Strover", age: 34, gender: "Female", group: "Family", state: "Texas"),
        User(name: "Eliza Tregien", age: 38, gender: "Female", group: "Friend", state: "North Carolina"),
        User(name: "Hurlee Loker", age: 44, gender: "Male", group: "Work", state: "Colorado"),
        User(name: "Orlan Joesbury", age: 36, gender: "Male", group: "Family", state: "Kentucky"),
        User(name: "Berrie Lett", age: 32, gender: "Female", group: "Family", state: "California"),
        User(name: "Edythe Gregorio", age: 40, gender: "Female", group: "Family", state: "District of Columbia"),
        User(name: "Alys Hessle", age: 20, gender: "Female", group: "Family", state: "Maryland"),
        User(name: "Chrissie Forryan", age: 42, gender: "Male", group: "Work", state: "Florida"),
        User(name: "Ervin Chevin", age: 40, gender: "Male", group: "Work", state: "Indiana"),
        User(name: "Trey Kliesl", age: 50, gender: "Male", group: "Family", state: "North Carolina"),
        User(name: "Rozele Gresly", age: 44, gender: "Female", group: "Family", state: "West Virginia"),
        User(name: "Hobart McGeagh", age: 22, gender: "Male", group: "Work", state: "New Jersey"),
        User(name: "Thayne Stennings", age: 44, gender: "Male", group: "Family", state: "West Virginia"),
        User(name: "Annabel Codman", age: 34, gender: "Female", group: "Family", state: "California"),
        User(name: "Carine Shegog", age: 34, gender: "Female", group: "Family", state: "Minnesota"),
        User(name: "Clem Uebel", age: 44, gender: "Male", group: "Friend", state: "Colorado"),
        User(name: "Bertrand Cardoo", age: 28, gender: "Male", group: "Friend", state: "Virginia"),
        User(name: "Humberto Shropshire", age: 40, gender: "Male", group: "Friend", state: "Delaware"),
        User(name: "Issie Lackney", age: 26, gender: "Female", group: "Work", state: "Florida"),
        User(name: "Etan Gorries", age: 46, gender: "Male", group: "Friend", state: "Nevada"),
        User(name: "Clo Arne", age: 32, gender: "Female", group: "Friend", state: "Ohio"),
        User(name: "Adora Ruggiero", age: 30, gender: "Female", group: "Friend", state: "New York"),
        User(name: "Joycelin Timlett", age: 48, gender: "Female", group: "Family", state: "Michigan"),
        User(name: "Joye Maldin", age: 22, gender: "Female", group: "Friend", state: "Florida"),
        User(name: "Annaliese Casterou", age: 24, gender: "Female", group: "Family", state: "Virginia"),
        User(name: "Filbert Allwright", age: 50, gender: "Male", group: "Family", state: "New York"),
        User(name: "Analise O'Shesnan", age: 48, gender: "Female", group: "Friend", state: "Indiana"),
        User(name: "Ransom Mallall", age: 22, gender: "Male", group: "Work", state: "Mississippi"),
        User(name: "Dolph Senecaux", age: 42, gender: "Male", group: "Work", state: "Connecticut"),
        User(name: "Faustine Davidov", age: 26, gender: "Female", group: "Work", state: "Louisiana"),
        User(name: "Ronni Camellini", age: 30, gender: "Female", group: "Friend", state: "Ohio"),
        User(name: "Filia McKeggie", age: 20, gender: "Female", group: "Friend", state: "Texas"),
        User(name: "Jolie Sheber", age: 44, gender: "Female", group: "Work", state: "North Carolina"),
        User(name: "Gillan Punchard", age: 34, gender: "Female", group: "Work", state: "New Mexico"),
        User(name: "Reid Simmens", age: 26, gender: "Male", group: "Friend", state: "California"),
        User(name: "Halette Leaton", age: 28, gender: "Female", group: "Work", state: "Illinois"),
        User(name: "Grace Petegre", age: 32, gender: "Male", group: "Friend", state: "Arkansas"),
        User(name: "Janenna Nulty", age: 48, gender: "Female", group: "Work", state: "Hawaii"),
        User(name: "Mike McQueen", age: 44, gender: "Male", group: "Family", state: "Florida"),
        User(name: "Cristi Sherr", age: 22, gender: "Female", group: "Friend", state: "Georgia"),
        User(name: "Garrott Pierton", age: 36, gender: "Male", group: "Work", state: "Nevada"),
        User(name: "Ibbie Kemet", age: 38, gender: "Female", group: "Family", state: "Hawaii"),
        User(name: "Sacha Cordet", age: 38, gender: "Female", group: "Work", state: "Ohio"),
        User(name: "Cathe Butner", age: 28, gender: "Female", group: "Family", state: "Florida"),
        User(name: "Immanuel Kreber", age: 32, gender: "Male", group: "Family", state: "Colorado"),
        User(name: "Mireille Hutson", age: 36, gender: "Female", group: "Friend", state: "Florida"),
        User(name: "Xavier Diplock", age: 36, gender: "Male", group: "Friend", state: "Alabama"),
        User(name: "Donia Coxhell", age: 22, gender: "Female", group: "Friend", state: "Iowa"),
        User(name: "Nikoletta Desouza", age: 42, gender: "Female", group: "Work", state: "Oklahoma"),
        User(name: "Delainey Whitford", age: 24, gender: "Male", group: "Work", state: "Florida"),
        User(name: "Consolata McKendo", age: 46, gender: "Female", group: "Family", state: "Georgia"),
        User(name: "Thedric Emblen", age: 36, gender: "Male", group: "Family", state: "Florida"),
        User(name: "Murial cornhill", age: 36, gender: "Female", group: "Work", state: "Iowa"),
        User(name: "Alric Brastead", age: 38, gender: "Male", group: "Work", state: "Tennessee"),
        User(name: "Rea Evenett", age: 30, gender: "Female", group: "Friend", state: "Connecticut"),
        User(name: "Arabele Duesberry", age: 34, gender: "Female", group: "Work", state: "Michigan"),
        User(name: "Xenia Duffitt", age: 38, gender: "Female", group: "Work", state: "Alabama"),
        User(name: "Pris O'Leary", age: 44, gender: "Female", group: "Family", state: "Delaware"),
        User(name: "Donnamarie Gorton", age: 34, gender: "Female", group: "Work", state: "Texas"),
        User(name: "Mabelle Threadgold", age: 34, gender: "Female", group: "Work", state: "Florida"),
        User(name: "Aila Spick", age: 20, gender: "Female", group: "Friend", state: "Texas"),
        User(name: "Oren Thurlby", age: 44, gender: "Male", group: "Family", state: "California"),
        User(name: "Olivette Lampen", age: 24, gender: "Female", group: "Family", state: "Texas"),
        User(name: "Saudra Barkhouse", age: 24, gender: "Female", group: "Family", state: "Florida"),
        User(name: "Bevan Castellucci", age: 44, gender: "Male", group: "Work", state: "Ohio"),
        User(name: "Sonnie Hanbidge", age: 44, gender: "Female", group: "Friend", state: "Pennsylvania"),
        User(name: "Loy Denslow", age: 22, gender: "Male", group: "Family", state: "Texas"),
        User(name: "Mona Sefton", age: 26, gender: "Female", group: "Friend", state: "Wisconsin"),
        User(name: "Jeremias Manoch", age: 38, gender: "Male", group: "Family", state: "California"),
        User(name: "Miguelita Jori", age: 24, gender: "Female", group: "Family", state: "Tennessee"),
        User(name: "Obediah Eastwell", age: 32, gender: "Male", group: "Friend", state: "Colorado"),
        User(name: "Al Tallant", age: 44, gender: "Male", group: "Family", state: "Georgia"),
        User(name: "Artemus Durram", age: 46, gender: "Male", group: "Work", state: "Ohio"),
        User(name: "Tan Klimes", age: 26, gender: "Male", group: "Friend", state: "Minnesota"),
        User(name: "Abraham Pickover", age: 24, gender: "Male", group: "Family", state: "Illinois"),
        User(name: "Oralla Durtnall", age: 42, gender: "Female", group: "Friend", state: "Virginia"),
        User(name: "Farrah Dearlove", age: 38, gender: "Female", group: "Work", state: "Texas"),
        User(name: "Moses Petrillo", age: 32, gender: "Male", group: "Work", state: "Maryland"),
        User(name: "Haze Scrymgeour", age: 34, gender: "Male", group: "Work", state: "Alabama"),
        User(name: "Adrian Tregale", age: 44, gender: "Male", group: "Family", state: "New Jersey"),
        User(name: "Gwyneth Pillman", age: 44, gender: "Female", group: "Friend", state: "Georgia"),
        User(name: "Whitby Leatt", age: 24, gender: "Male", group: "Work", state: "Oklahoma"),
        User(name: "Nancie Gwinnett", age: 20, gender: "Female", group: "Family", state: "Florida"),
        User(name: "Baudoin Karlsen", age: 36, gender: "Male", group: "Work", state: "Oklahoma"),
        User(name: "Konrad Howson", age: 24, gender: "Male", group: "Family", state: "Colorado"),
        User(name: "Nerti Littlepage", age: 22, gender: "Female", group: "Friend", state: "Colorado"),
        User(name: "Broderick Ingilson", age: 50, gender: "Male", group: "Work", state: "Texas"),
        User(name: "Sabra Gadsdon", age: 30, gender: "Female", group: "Family", state: "Iowa"),
        User(name: "Josefina Leser", age: 46, gender: "Female", group: "Friend", state: "New York"),
        User(name: "Luisa Ticehurst", age: 50, gender: "Female", group: "Work", state: "New York"),
        User(name: "Junia Craxford", age: 20, gender: "Female", group: "Family", state: "Indiana"),
        User(name: "Ralph Salmond", age: 20, gender: "Male", group: "Family", state: "Texas"),
        User(name: "Katrine Roubeix", age: 48, gender: "Female", group: "Friend", state: "Missouri"),
        User(name: "Maxim Megarry", age: 36, gender: "Male", group: "Family", state: "Ohio"),
        User(name: "Lilla Wisedale", age: 36, gender: "Female", group: "Work", state: "Connecticut"),
        User(name: "Herman Lannen", age: 34, gender: "Male", group: "Family", state: "Texas"),
        User(name: "Lucais Norsister", age: 34, gender: "Male", group: "Work", state: "California"),
        User(name: "Stanton Seide", age: 38, gender: "Male", group: "Friend", state: "Alabama"),
        User(name: "Maegan Peerless", age: 22, gender: "Female", group: "Work", state: "Louisiana"),
        User(name: "Chilton Shirer", age: 44, gender: "Male", group: "Work", state: "New Jersey"),
        User(name: "Calli Applegate", age: 42, gender: "Female", group: "Family", state: "Iowa"),
        User(name: "Fransisco Frayn", age: 26, gender: "Male", group: "Family", state: "California"),
        User(name: "Kimberley Jurges", age: 26, gender: "Female", group: "Family", state: "Louisiana"),
        User(name: "Oates Brotherick", age: 24, gender: "Male", group: "Friend", state: "Pennsylvania"),
        User(name: "Duncan Potts", age: 22, gender: "Male", group: "Work", state: "Colorado"),
        User(name: "Tony Caddie", age: 38, gender: "Female", group: "Friend", state: "Texas"),
        User(name: "Shoshanna Basnall", age: 40, gender: "Female", group: "Family", state: "California"),
        User(name: "Hersh Glassman", age: 28, gender: "Male", group: "Work", state: "Texas"),
        User(name: "Letta Hale", age: 42, gender: "Female", group: "Work", state: "California"),
        User(name: "Horacio Beat", age: 30, gender: "Male", group: "Work", state: "California"),
        User(name: "Amara McElroy", age: 44, gender: "Female", group: "Friend", state: "Florida"),
        User(name: "Viv Amort", age: 32, gender: "Female", group: "Family", state: "Florida"),
        User(name: "Minette Lally", age: 34, gender: "Female", group: "Family", state: "Texas"),
        User(name: "Rowland Serle", age: 32, gender: "Male", group: "Friend", state: "Idaho"),
        User(name: "Cynthy Siverns", age: 40, gender: "Female", group: "Work", state: "Georgia"),
        User(name: "Norma Weepers", age: 42, gender: "Female", group: "Work", state: "Virginia"),
        User(name: "Adrian Goschalk", age: 30, gender: "Female", group: "Work", state: "District of Columbia"),
        User(name: "Angelo Dreinan", age: 26, gender: "Male", group: "Work", state: "Oklahoma"),
        User(name: "Talbot Brithman", age: 24, gender: "Male", group: "Friend", state: "Maryland"),
        User(name: "Doralia Madden", age: 30, gender: "Female", group: "Family", state: "New York"),
        User(name: "Odell Opdenorth", age: 34, gender: "Male", group: "Work", state: "Illinois"),
        User(name: "Kelvin Maber", age: 36, gender: "Male", group: "Friend", state: "Ohio"),
        User(name: "Josepha Capes", age: 46, gender: "Female", group: "Friend", state: "Washington"),
        User(name: "Jessey Emons", age: 30, gender: "Male", group: "Friend", state: "Missouri"),
        User(name: "Mirna Ingarfill", age: 22, gender: "Female", group: "Work", state: "Illinois"),
        User(name: "Fredrika Bulman", age: 34, gender: "Female", group: "Friend", state: "South Carolina"),
        User(name: "Gwenora MacAllester", age: 44, gender: "Female", group: "Family", state: "Texas"),
        User(name: "Kippar Cassel", age: 24, gender: "Male", group: "Work", state: "District of Columbia"),
        User(name: "Nickolai Angove", age: 32, gender: "Male", group: "Friend", state: "Florida"),
        User(name: "Ema Rodolf", age: 30, gender: "Female", group: "Work", state: "Illinois"),
        User(name: "Ethe Stoodale", age: 28, gender: "Male", group: "Friend", state: "Louisiana"),
        User(name: "Nealy Lill", age: 40, gender: "Male", group: "Work", state: "California"),
        User(name: "Alwin Dearle", age: 38, gender: "Male", group: "Work", state: "Connecticut"),
        User(name: "Khalil Mar", age: 48, gender: "Male", group: "Family", state: "Georgia"),
        User(name: "Meg Sansome", age: 40, gender: "Female", group: "Friend", state: "Florida"),
        User(name: "Malanie Balsillie", age: 44, gender: "Female", group: "Family", state: "Pennsylvania"),
        User(name: "Niels Challiner", age: 50, gender: "Male", group: "Family", state: "West Virginia"),
        User(name: "Maurise Huscroft", age: 32, gender: "Male", group: "Friend", state: "District of Columbia"),
        User(name: "Rozamond Martensen", age: 28, gender: "Female", group: "Family", state: "Connecticut"),
        User(name: "Stanfield Verzey", age: 38, gender: "Male", group: "Family", state: "North Carolina"),
        User(name: "Chadwick Remer", age: 26, gender: "Male", group: "Work", state: "Texas"),
        User(name: "Wenona Shemmin", age: 48, gender: "Female", group: "Family", state: "Ohio"),
        User(name: "Ardelis Snoding", age: 42, gender: "Female", group: "Friend", state: "New York"),
        User(name: "Carena Downie", age: 36, gender: "Female", group: "Work", state: "Illinois"),
        User(name: "Lucky Crafter", age: 48, gender: "Female", group: "Work", state: "Florida"),
        User(name: "Thain Gauld", age: 44, gender: "Male", group: "Family", state: "Virginia"),
        User(name: "Etta Boyde", age: 40, gender: "Female", group: "Family", state: "Virginia"),
        User(name: "Georgiana Gregorowicz", age: 28, gender: "Female", group: "Friend", state: "Florida"),
        User(name: "Mirelle Favey", age: 48, gender: "Female", group: "Friend", state: "Arizona"),
        User(name: "Arabele Edwardes", age: 38, gender: "Female", group: "Work", state: "Florida"),
        User(name: "Beulah Beecker", age: 30, gender: "Female", group: "Family", state: "California"),
        User(name: "Jobi De la Feld", age: 28, gender: "Female", group: "Work", state: "Texas"),
        User(name: "Isac Oels", age: 34, gender: "Male", group: "Family", state: "Florida"),
        User(name: "Jennilee Chatelain", age: 32, gender: "Female", group: "Work", state: "Illinois"),
        User(name: "Appolonia Cathery", age: 22, gender: "Female", group: "Friend", state: "Oregon"),
        User(name: "Domingo Courtin", age: 24, gender: "Male", group: "Friend", state: "District of Columbia"),
        User(name: "Tanny Edmett", age: 48, gender: "Male", group: "Friend", state: "Utah"),
        User(name: "Konstance Snoding", age: 38, gender: "Female", group: "Work", state: "Florida"),
        User(name: "Collen Symms", age: 28, gender: "Female", group: "Family", state: "New York"),
        User(name: "Tobe Mohamed", age: 28, gender: "Female", group: "Family", state: "New York"),
        User(name: "Brad Tierny", age: 36, gender: "Male", group: "Work", state: "Arizona"),
        User(name: "Eddie Eick", age: 24, gender: "Female", group: "Work", state: "California"),
        User(name: "Hewet Haynes", age: 48, gender: "Male", group: "Friend", state: "Florida"),
        User(name: "Paulie Aleevy", age: 32, gender: "Female", group: "Friend", state: "Minnesota"),
        User(name: "Clemente Hendrix", age: 38, gender: "Male", group: "Friend", state: "Illinois"),
        User(name: "Susan Buswell", age: 44, gender: "Female", group: "Work", state: "Kansas"),
        User(name: "Karyl Hannant", age: 32, gender: "Female", group: "Work", state: "Washington"),
        User(name: "Corrie Flade", age: 26, gender: "Female", group: "Work", state: "Florida"),
        User(name: "Reade McCumesky", age: 38, gender: "Male", group: "Family", state: "California"),
        User(name: "Fran Riall", age: 34, gender: "Female", group: "Friend", state: "Minnesota"),
        User(name: "Ellene Wyness", age: 44, gender: "Female", group: "Work", state: "Nevada"),
        User(name: "Giffy Brisard", age: 38, gender: "Male", group: "Family", state: "Florida"),
        User(name: "Victor Westoff", age: 40, gender: "Male", group: "Friend", state: "Texas"),
        User(name: "Pierette Wilber", age: 50, gender: "Female", group: "Work", state: "Iowa"),
        User(name: "Loralee MacKerley", age: 46, gender: "Female", group: "Work", state: "District of Columbia"),
        User(name: "Clerc Cavee", age: 38, gender: "Male", group: "Work", state: "Texas"),
        User(name: "Seymour Gladyer", age: 28, gender: "Male", group: "Work", state: "Indiana"),
        User(name: "Jobye Atyea", age: 46, gender: "Female", group: "Family", state: "Ohio"),
        User(name: "Tiffi McLaughlan", age: 40, gender: "Female", group: "Friend", state: "Tennessee"),
        User(name: "Edgar Gatfield", age: 34, gender: "Male", group: "Work", state: "Kentucky"),
        User(name: "Cesare Kolis", age: 32, gender: "Male", group: "Family", state: "Nebraska"),
        User(name: "Essie Ramas", age: 30, gender: "Female", group: "Family", state: "Texas"),
        User(name: "Toma Jeynes", age: 20, gender: "Female", group: "Friend", state: "Tennessee"),
        User(name: "Dud Hunnybun", age: 50, gender: "Male", group: "Friend", state: "Texas"),
        User(name: "Dania Troak", age: 30, gender: "Female", group: "Work", state: "New York"),
        User(name: "Gerianna Spiaggia", age: 28, gender: "Female", group: "Friend", state: "Massachusetts"),
        User(name: "Osmund Stagge", age: 30, gender: "Male", group: "Family", state: "Louisiana"),
        User(name: "Fitzgerald Kruger", age: 24, gender: "Male", group: "Family", state: "Louisiana"),
        User(name: "Olympie Goodisson", age: 36, gender: "Female", group: "Friend", state: "West Virginia"),
        User(name: "Kelley Rudwell", age: 34, gender: "Male", group: "Work", state: "New York"),
        User(name: "Millard Bowring", age: 20, gender: "Male", group: "Friend", state: "Florida"),
        User(name: "Clemente Bricknall", age: 30, gender: "Male", group: "Friend", state: "Alabama"),
        User(name: "Kennan Broadfield", age: 26, gender: "Male", group: "Family", state: "Connecticut"),
        User(name: "Chucho Coneley", age: 38, gender: "Male", group: "Work", state: "Texas"),
        User(name: "Timotheus Georg", age: 44, gender: "Male", group: "Work", state: "Ohio"),
        User(name: "Humbert Coppens", age: 24, gender: "Male", group: "Family", state: "Massachusetts"),
        User(name: "Janine Bentley", age: 40, gender: "Female", group: "Work", state: "Utah"),
        User(name: "Eduino Snelle", age: 44, gender: "Male", group: "Family", state: "Illinois"),
        User(name: "Gayle Siebert", age: 26, gender: "Male", group: "Friend", state: "Texas"),
        User(name: "Leontine Pilbeam", age: 36, gender: "Female", group: "Work", state: "California"),
        User(name: "Rosella Lehr", age: 36, gender: "Female", group: "Work", state: "Michigan"),
        User(name: "Blondie Urlin", age: 24, gender: "Female", group: "Friend", state: "California"),
        User(name: "Valeda Snasdell", age: 34, gender: "Female", group: "Family", state: "South Dakota"),
        User(name: "Hamnet Streather", age: 30, gender: "Male", group: "Friend", state: "Arkansas"),
        User(name: "Hanson Althrope", age: 32, gender: "Male", group: "Work", state: "Connecticut"),
        User(name: "Christophorus Morais", age: 50, gender: "Male", group: "Family", state: "California"),
        User(name: "Kev Medford", age: 36, gender: "Male", group: "Family", state: "Texas"),
        User(name: "Gwenni Scandrett", age: 48, gender: "Female", group: "Family", state: "Kansas"),
        User(name: "Horace Whittier", age: 48, gender: "Male", group: "Family", state: "California"),
        User(name: "Josephine Kopp", age: 26, gender: "Female", group: "Work", state: "District of Columbia"),
        User(name: "Chrisy Taffee", age: 32, gender: "Male", group: "Friend", state: "Ohio"),
        User(name: "Aldo Hannaway", age: 44, gender: "Male", group: "Friend", state: "Florida"),
        User(name: "Markus Firsby", age: 26, gender: "Male", group: "Family", state: "Washington"),
        User(name: "Norma Rummings", age: 46, gender: "Female", group: "Work", state: "New York"),
        User(name: "Giorgio Wortley", age: 48, gender: "Male", group: "Work", state: "Oklahoma"),
        User(name: "Sander Pinyon", age: 30, gender: "Male", group: "Friend", state: "Virginia"),
        User(name: "Ilene Duckerin", age: 32, gender: "Female", group: "Work", state: "Illinois"),
        User(name: "Amble Brixham", age: 30, gender: "Male", group: "Work", state: "Pennsylvania"),
        User(name: "Grange Hearnshaw", age: 46, gender: "Male", group: "Friend", state: "New York"),
        User(name: "Roxie Absalom", age: 34, gender: "Female", group: "Work", state: "Texas"),
        User(name: "Lowell Paradin", age: 30, gender: "Male", group: "Friend", state: "Washington"),
        User(name: "Ashby Grisbrook", age: 38, gender: "Male", group: "Friend", state: "Texas"),
        User(name: "Celinda Ludlam", age: 38, gender: "Female", group: "Family", state: "New Jersey"),
        User(name: "Donalt Burtwell", age: 30, gender: "Male", group: "Work", state: "California"),
        User(name: "Elsy Matthis", age: 32, gender: "Female", group: "Work", state: "Ohio"),
        User(name: "Jefferson Juett", age: 44, gender: "Male", group: "Work", state: "California"),
        User(name: "Warde Bick", age: 24, gender: "Male", group: "Friend", state: "Alabama"),
        User(name: "Davon Mathwin", age: 50, gender: "Male", group: "Friend", state: "Illinois"),
        User(name: "Franky Brackenbury", age: 40, gender: "Female", group: "Friend", state: "New York"),
        User(name: "Ainslie Huband", age: 40, gender: "Female", group: "Friend", state: "California"),
        User(name: "Jone Pascho", age: 24, gender: "Male", group: "Work", state: "New York"),
        User(name: "Jonathan Bohlmann", age: 26, gender: "Male", group: "Work", state: "New Mexico"),
        User(name: "Dixie Shilstone", age: 26, gender: "Female", group: "Family", state: "California"),
        User(name: "Roscoe Liffey", age: 24, gender: "Male", group: "Work", state: "California"),
        User(name: "Tresa Mandeville", age: 48, gender: "Female", group: "Friend", state: "Missouri"),
        User(name: "Doug Mulbery", age: 22, gender: "Male", group: "Work", state: "Nevada"),
        User(name: "Dannie Heggison", age: 24, gender: "Male", group: "Work", state: "Tennessee"),
        User(name: "Cordi Simeons", age: 28, gender: "Female", group: "Family", state: "Ohio"),
        User(name: "Nonna Lander", age: 24, gender: "Female", group: "Family", state: "Pennsylvania"),
        User(name: "Dannie Kennefick", age: 40, gender: "Female", group: "Friend", state: "Illinois"),
        User(name: "Krishnah Gowry", age: 30, gender: "Male", group: "Family", state: "West Virginia"),
        User(name: "Katalin O'Mohun", age: 44, gender: "Female", group: "Work", state: "South Carolina"),
        User(name: "Emmi Nasey", age: 38, gender: "Female", group: "Work", state: "Georgia"),
        User(name: "Breena Wickes", age: 48, gender: "Female", group: "Friend", state: "Michigan"),
        User(name: "Portia July", age: 38, gender: "Female", group: "Family", state: "Texas"),
        User(name: "Adelind Habard", age: 30, gender: "Female", group: "Friend", state: "Florida"),
        User(name: "Ailyn Cordeiro", age: 26, gender: "Female", group: "Friend", state: "Massachusetts"),
        User(name: "Hobey Warkup", age: 34, gender: "Male", group: "Family", state: "Georgia"),
        User(name: "Valera Walton", age: 40, gender: "Female", group: "Family", state: "New York"),
        User(name: "Susanetta Rymell", age: 42, gender: "Female", group: "Work", state: "Texas"),
        User(name: "Fransisco Daudray", age: 38, gender: "Male", group: "Family", state: "Idaho"),
        User(name: "Edlin Folliss", age: 26, gender: "Male", group: "Work", state: "New York"),
        User(name: "Rudie Pendlebury", age: 30, gender: "Male", group: "Family", state: "Nevada"),
        User(name: "Chet Sendall", age: 32, gender: "Male", group: "Work", state: "Virginia"),
        User(name: "Findlay Lockett", age: 36, gender: "Male", group: "Family", state: "California"),
        User(name: "Iago Glading", age: 34, gender: "Male", group: "Friend", state: "Kansas"),
        User(name: "Mandel Van Son", age: 24, gender: "Male", group: "Friend", state: "Illinois"),
        User(name: "Ricki Babonau", age: 42, gender: "Male", group: "Friend", state: "California"),
        User(name: "Jake Eliet", age: 36, gender: "Male", group: "Friend", state: "Texas"),
        User(name: "Tomi Withinshaw", age: 22, gender: "Female", group: "Work", state: "Minnesota"),
        User(name: "Giffie Frediani", age: 34, gender: "Male", group: "Work", state: "California"),
        User(name: "Neely Fifield", age: 48, gender: "Female", group: "Family", state: "Florida"),
        User(name: "Hamid Smail", age: 24, gender: "Male", group: "Family", state: "Georgia"),
        User(name: "Gael Ibarra", age: 44, gender: "Female", group: "Work", state: "Florida"),
        User(name: "Bary Marieton", age: 40, gender: "Male", group: "Friend", state: "Minnesota"),
        User(name: "Felicia Benedick", age: 30, gender: "Female", group: "Work", state: "Michigan"),
        User(name: "Bendick MacGragh", age: 40, gender: "Male", group: "Friend", state: "Delaware"),
        User(name: "Carmon Dowell", age: 32, gender: "Female", group: "Friend", state: "Alabama"),
        User(name: "Elsey Sayre", age: 30, gender: "Female", group: "Work", state: "North Carolina"),
        User(name: "Stormie Becks", age: 50, gender: "Female", group: "Family", state: "Louisiana"),
        User(name: "Morey Deering", age: 32, gender: "Male", group: "Family", state: "Texas"),
        User(name: "Aryn Madill", age: 32, gender: "Female", group: "Work", state: "New York"),
        User(name: "Barbaraanne Pridgeon", age: 36, gender: "Female", group: "Work", state: "Colorado"),
        User(name: "Krispin Gouldthorpe", age: 26, gender: "Male", group: "Family", state: "Texas"),
        User(name: "Traci Regnard", age: 26, gender: "Female", group: "Family", state: "Missouri"),
        User(name: "Myrilla Brobyn", age: 24, gender: "Female", group: "Work", state: "Texas"),
        User(name: "Dorey Cathel", age: 38, gender: "Female", group: "Work", state: "New York"),
        User(name: "Isaak Reubens", age: 48, gender: "Male", group: "Work", state: "Michigan"),
        User(name: "Ardelle Charnley", age: 48, gender: "Female", group: "Family", state: "District of Columbia"),
        User(name: "Mackenzie Tregidgo", age: 46, gender: "Male", group: "Work", state: "Minnesota"),
        User(name: "Putnem Carlone", age: 40, gender: "Male", group: "Work", state: "Idaho"),
        User(name: "Artair Deniskevich", age: 34, gender: "Male", group: "Family", state: "Massachusetts"),
        User(name: "Grady Winscom", age: 22, gender: "Male", group: "Friend", state: "Texas"),
        User(name: "Care Fison", age: 26, gender: "Male", group: "Family", state: "Alabama"),
        User(name: "Katlin Aplin", age: 50, gender: "Female", group: "Work", state: "Tennessee"),
        User(name: "Dukey Wannell", age: 22, gender: "Male", group: "Work", state: "Texas"),
        User(name: "Marti Sainz", age: 20, gender: "Female", group: "Friend", state: "Maryland"),
        User(name: "Nanni Longhi", age: 28, gender: "Female", group: "Work", state: "California"),
        User(name: "Tisha Skeat", age: 46, gender: "Female", group: "Work", state: "Florida"),
        User(name: "Zachary Gerritzen", age: 22, gender: "Male", group: "Family", state: "Florida"),
        User(name: "Welch Bazeley", age: 34, gender: "Male", group: "Work", state: "Missouri"),
        User(name: "Betti Farncomb", age: 44, gender: "Female", group: "Friend", state: "Louisiana"),
        User(name: "Andree Figgen", age: 26, gender: "Female", group: "Family", state: "Louisiana"),
        User(name: "Earl Mawdsley", age: 46, gender: "Male", group: "Family", state: "New York"),
        User(name: "Loydie Oakley", age: 30, gender: "Male", group: "Work", state: "California"),
        User(name: "Micah Camoys", age: 40, gender: "Male", group: "Friend", state: "Louisiana"),
        User(name: "Gillie Macveigh", age: 30, gender: "Female", group: "Family", state: "Oklahoma"),
        User(name: "Hobart Karlsen", age: 24, gender: "Male", group: "Friend", state: "California"),
        User(name: "Kriste Polhill", age: 26, gender: "Female", group: "Friend", state: "North Carolina"),
        User(name: "Rozanne McSpirron", age: 22, gender: "Female", group: "Family", state: "District of Columbia"),
        User(name: "Norma Michelmore", age: 40, gender: "Female", group: "Family", state: "Pennsylvania"),
        User(name: "Rivkah Sprott", age: 32, gender: "Female", group: "Friend", state: "Georgia"),
        User(name: "Lonee Faulkes", age: 40, gender: "Female", group: "Work", state: "Florida"),
        User(name: "Curry Dagless", age: 22, gender: "Male", group: "Work", state: "Pennsylvania"),
        User(name: "Viviana Caldera", age: 20, gender: "Female", group: "Family", state: "Colorado"),
        User(name: "Eddie Wyer", age: 38, gender: "Female", group: "Work", state: "New York"),
        User(name: "Laryssa Castaignet", age: 26, gender: "Female", group: "Family", state: "Texas"),
        User(name: "Merline Dorricott", age: 22, gender: "Female", group: "Work", state: "Indiana"),
        User(name: "Sharleen Puddan", age: 32, gender: "Female", group: "Family", state: "Texas"),
        User(name: "Jill Wilks", age: 50, gender: "Female", group: "Friend", state: "Texas"),
        User(name: "Sigfrid Hinsch", age: 50, gender: "Male", group: "Work", state: "Virginia"),
        User(name: "Alexander Hugnet", age: 34, gender: "Male", group: "Work", state: "Texas"),
        User(name: "Laureen Honatsch", age: 48, gender: "Female", group: "Work", state: "Pennsylvania"),
        User(name: "Carmella Godehard.sf", age: 30, gender: "Female", group: "Work", state: "Ohio"),
        User(name: "Theressa Fiorentino", age: 48, gender: "Female", group: "Work", state: "Florida"),
        User(name: "Derwin Netting", age: 36, gender: "Male", group: "Family", state: "Connecticut"),
        User(name: "Janaye Mingauld", age: 44, gender: "Female", group: "Work", state: "Pennsylvania"),
        User(name: "Quintana Trollope", age: 36, gender: "Female", group: "Family", state: "Pennsylvania"),
        User(name: "Cherilynn Doudny", age: 26, gender: "Female", group: "Work", state: "District of Columbia"),
        User(name: "Nicole Sommerled", age: 20, gender: "Female", group: "Friend", state: "Delaware"),
        User(name: "Val Wathan", age: 30, gender: "Female", group: "Friend", state: "Delaware"),
        User(name: "Ivett Mackilpatrick", age: 38, gender: "Female", group: "Friend", state: "Florida"),
        User(name: "Maurice Iddon", age: 46, gender: "Male", group: "Work", state: "New Jersey"),
        User(name: "Gery Janouch", age: 32, gender: "Male", group: "Friend", state: "New Mexico"),
        User(name: "Win Waltering", age: 36, gender: "Male", group: "Family", state: "Oklahoma"),
        User(name: "Deni Dommett", age: 22, gender: "Female", group: "Work", state: "Michigan"),
        User(name: "Sonni Cosser", age: 48, gender: "Female", group: "Friend", state: "California"),
        User(name: "Sayre Armor", age: 38, gender: "Female", group: "Friend", state: "Virginia"),
        User(name: "Donnell Mousdall", age: 38, gender: "Male", group: "Family", state: "Minnesota"),
        User(name: "Timmy Towndrow", age: 30, gender: "Male", group: "Work", state: "Pennsylvania"),
        User(name: "Ivory Facer", age: 22, gender: "Female", group: "Family", state: "Florida"),
        User(name: "Eilis Fullalove", age: 22, gender: "Female", group: "Friend", state: "Colorado"),
        User(name: "Tedra McMechan", age: 32, gender: "Female", group: "Friend", state: "Florida"),
        User(name: "Lucinda Shear", age: 28, gender: "Female", group: "Work", state: "District of Columbia"),
        User(name: "Brigham Domini", age: 46, gender: "Male", group: "Friend", state: "Missouri"),
        User(name: "Urbano Eggle", age: 32, gender: "Male", group: "Family", state: "Pennsylvania"),
        User(name: "Donavon Mincini", age: 24, gender: "Male", group: "Work", state: "Minnesota"),
        User(name: "Devonna Bulfit", age: 32, gender: "Female", group: "Work", state: "Florida"),
        User(name: "Winslow Warboy", age: 46, gender: "Male", group: "Family", state: "California"),
        User(name: "Daisie Caldroni", age: 28, gender: "Female", group: "Work", state: "Alabama"),
        User(name: "Rozalie Damarell", age: 30, gender: "Female", group: "Family", state: "Florida"),
        User(name: "Jesselyn Panner", age: 20, gender: "Female", group: "Family", state: "Indiana"),
        User(name: "Hagan Worrell", age: 48, gender: "Male", group: "Family", state: "Georgia"),
        User(name: "Andy Ary", age: 30, gender: "Male", group: "Family", state: "California"),
        User(name: "Lonnie Barbary", age: 40, gender: "Female", group: "Family", state: "Florida"),
        User(name: "Ignaz Ackers", age: 26, gender: "Male", group: "Work", state: "Indiana"),
        User(name: "Rosalyn Farbrother", age: 32, gender: "Female", group: "Family", state: "Texas"),
        User(name: "Bernice Blune", age: 38, gender: "Female", group: "Friend", state: "Colorado"),
        User(name: "Oliy Gianolini", age: 22, gender: "Female", group: "Family", state: "California"),
        User(name: "Pavia Perceval", age: 24, gender: "Female", group: "Family", state: "Texas"),
        User(name: "Haley Belfrage", age: 36, gender: "Male", group: "Family", state: "Texas"),
        User(name: "Rainer Wrist", age: 36, gender: "Male", group: "Friend", state: "New Jersey"),
        User(name: "Tye Ormiston", age: 34, gender: "Male", group: "Friend", state: "Georgia"),
        User(name: "Lloyd Sent", age: 46, gender: "Male", group: "Family", state: "California"),
        User(name: "Mina Runcie", age: 22, gender: "Female", group: "Friend", state: "West Virginia"),
        User(name: "Quincey McLucas", age: 24, gender: "Male", group: "Family", state: "Pennsylvania"),
        User(name: "Bebe Sharvell", age: 36, gender: "Female", group: "Friend", state: "California"),
        User(name: "Hamid Lounds", age: 22, gender: "Male", group: "Work", state: "Missouri"),
        User(name: "Mariann Winsper", age: 38, gender: "Female", group: "Friend", state: "Texas"),
        User(name: "Alva Bony", age: 22, gender: "Male", group: "Friend", state: "Virginia"),
        User(name: "Orv Burdin", age: 34, gender: "Male", group: "Family", state: "Texas"),
        User(name: "Adrien Seavers", age: 30, gender: "Male", group: "Family", state: "Indiana"),
        User(name: "Edin Twiname", age: 46, gender: "Female", group: "Work", state: "North Carolina"),
        User(name: "Allene Alenichev", age: 36, gender: "Female", group: "Friend", state: "Florida"),
        User(name: "Caren Rose", age: 46, gender: "Female", group: "Work", state: "Ohio"),
        User(name: "Bobbette Britch", age: 40, gender: "Female", group: "Work", state: "Indiana"),
        User(name: "Rufe Marjot", age: 44, gender: "Male", group: "Family", state: "Minnesota"),
        User(name: "Mozelle Sapson", age: 36, gender: "Female", group: "Family", state: "Florida"),
        User(name: "Wally Lindenberg", age: 22, gender: "Male", group: "Family", state: "Oklahoma"),
        User(name: "Emelyne Quinnette", age: 26, gender: "Female", group: "Family", state: "Pennsylvania"),
        User(name: "Lura Avery", age: 30, gender: "Female", group: "Work", state: "New York"),
        User(name: "Sayers O'Spellissey", age: 34, gender: "Male", group: "Family", state: "California"),
        User(name: "Faunie Insole", age: 32, gender: "Female", group: "Work", state: "South Carolina"),
        User(name: "Lexie Emma", age: 50, gender: "Female", group: "Family", state: "California"),
        User(name: "Avril Fend", age: 34, gender: "Female", group: "Work", state: "California"),
        User(name: "Hersh Deegan", age: 40, gender: "Male", group: "Work", state: "California"),
        User(name: "Jeno Flahy", age: 26, gender: "Male", group: "Friend", state: "Massachusetts"),
        User(name: "Aubrette Gridley", age: 22, gender: "Female", group: "Work", state: "Kansas"),
        User(name: "Odey Lonergan", age: 24, gender: "Male", group: "Family", state: "Washington"),
        User(name: "Adelice Boagey", age: 30, gender: "Female", group: "Friend", state: "Florida"),
        User(name: "Milton Reisk", age: 42, gender: "Male", group: "Friend", state: "Georgia"),
        User(name: "Kary Parnell", age: 24, gender: "Female", group: "Family", state: "Florida"),
        User(name: "Charyl Furnell", age: 44, gender: "Female", group: "Work", state: "Wisconsin"),
        User(name: "Johan Lavigne", age: 32, gender: "Male", group: "Family", state: "Arizona")
    ]
}

