# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HW03' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HW03
  pod 'Alamofire', '4.8.1'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'AlamofireImage', '~> 3.5'

end
